#!/usr/bin/env bash
#
# ARG_HELP([iterativeN3 inhomogeneity correction])
# ARG_OPTIONAL_SINGLE([distance],[],[Initial distance for correction],[40])
# ARG_OPTIONAL_SINGLE([levels],[],[Levels of correction with distance halving],[4])
# ARG_OPTIONAL_SINGLE([cycles],[],[Cycles of correction at each level],[3])
# ARG_OPTIONAL_SINGLE([iters],[],[Iterations of correction for each cycle],[100])
# ARG_OPTIONAL_SINGLE([lambda],[],[Spline regularization value],[2.0e-6])
# ARG_OPTIONAL_SINGLE([fwhm],[],[Intensity histogram smoothing fwhm],[0.1])
# ARG_OPTIONAL_SINGLE([stop],[],[Stopping criterion for N3],[0.00001])
# ARG_OPTIONAL_SINGLE([isostep],[],[Isotropic resampling resolution in mm for N3],[0.3])
# ARG_OPTIONAL_BOOLEAN([big-misorientation],[],[Input file is very misoriented])

# ARG_OPTIONAL_SINGLE([model],[],[Reference model used for determining FOV and mask],[${QUARANTINE_PATH}/resources/Dorr_2008_Steadman_2013_Ullmann_2013_Richards_2011_Qiu_2016_Egan_2015_40micron/ex-vivo/DSURQE_40micron.mnc])
# ARG_OPTIONAL_SINGLE([model-mask],[],[Mask matching reference model],[${QUARANTINE_PATH}/resources/Dorr_2008_Steadman_2013_Ullmann_2013_Richards_2011_Qiu_2016_Egan_2015_40micron/ex-vivo/DSURQE_40micron_mask.mnc])

# ARG_OPTIONAL_BOOLEAN([clobber],[c],[Overwrite files that already exist])
# ARG_OPTIONAL_BOOLEAN([verbose],[v],[Run commands verbosely],[on])
# ARG_OPTIONAL_BOOLEAN([debug],[d],[Show all internal commands and logic for debug],[])
# ARG_POSITIONAL_SINGLE([input],[Input MINC or NIFTI file])
# ARG_POSITIONAL_SINGLE([output],[Output MINC or NIFTI File])
# ARGBASH_SET_INDENT([  ])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info

die() {
  local _ret="${2:-1}"
  test "${_PRINT_HELP:-no}" = yes && print_help >&2
  echo "$1" >&2
  exit "${_ret}"
}

begins_with_short_option() {
  local first_option all_short_options='hcvd'
  first_option="${1:0:1}"
  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_distance="40"
_arg_levels="4"
_arg_cycles="3"
_arg_iters="100"
_arg_lambda="2.0e-6"
_arg_fwhm="0.1"
_arg_stop="0.00001"
_arg_isostep="0.3"
_arg_big_misorientation="off"
_arg_model="${QUARANTINE_PATH}/resources/Dorr_2008_Steadman_2013_Ullmann_2013_Richards_2011_Qiu_2016_Egan_2015_40micron/ex-vivo/DSURQE_40micron.mnc"
_arg_model_mask="${QUARANTINE_PATH}/resources/Dorr_2008_Steadman_2013_Ullmann_2013_Richards_2011_Qiu_2016_Egan_2015_40micron/ex-vivo/DSURQE_40micron_mask.mnc"
_arg_clobber="off"
_arg_verbose="on"
_arg_debug="off"

print_help() {
  printf '%s\n' "iterativeN3 inhomogeneity correction"
  printf 'Usage: %s [-h|--help] [--distance <arg>] [--levels <arg>] [--cycles <arg>] [--iters <arg>] [--lambda <arg>] [--fwhm <arg>] [--stop <arg>] [--isostep <arg>] [--(no-)big-misorientation] [--model <arg>] [--model-mask <arg>] [-c|--(no-)clobber] [-v|--(no-)verbose] [-d|--(no-)debug] <input> <output>\n' "$0"
  printf '\t%s\n' "<input>: Input MINC or NIFTI file"
  printf '\t%s\n' "<output>: Output MINC or NIFTI File"
  printf '\t%s\n' "-h, --help: Prints help"
  printf '\t%s\n' "--distance: Initial distance for correction (default: '40')"
  printf '\t%s\n' "--levels: Levels of correction with distance halving (default: '4')"
  printf '\t%s\n' "--cycles: Cycles of correction at each level (default: '3')"
  printf '\t%s\n' "--iters: Iterations of correction for each cycle (default: '100')"
  printf '\t%s\n' "--lambda: Spline regularization value (default: '2.0e-6')"
  printf '\t%s\n' "--fwhm: Intensity histogram smoothing fwhm (default: '0.1')"
  printf '\t%s\n' "--stop: Stopping criterion for N3 (default: '0.00001')"
  printf '\t%s\n' "--isostep: Isotropic resampling resolution in mm for N3 (default: '0.3')"
  printf '\t%s\n' "--big-misorientation, --no-big-misorientation: Input file is very misoriented (off by default)"
  printf '\t%s\n' "--model: Reference model used for determining FOV and mask (default: '${QUARANTINE_PATH}/resources/Dorr_2008_Steadman_2013_Ullmann_2013_Richards_2011_Qiu_2016_Egan_2015_40micron/ex-vivo/DSURQE_40micron.mnc')"
  printf '\t%s\n' "--model-mask: Mask matching reference model (default: '${QUARANTINE_PATH}/resources/Dorr_2008_Steadman_2013_Ullmann_2013_Richards_2011_Qiu_2016_Egan_2015_40micron/ex-vivo/DSURQE_40micron_mask.mnc')"
  printf '\t%s\n' "-c, --clobber, --no-clobber: Overwrite files that already exist (off by default)"
  printf '\t%s\n' "-v, --verbose, --no-verbose: Run commands verbosely (on by default)"
  printf '\t%s\n' "-d, --debug, --no-debug: Show all internal commands and logic for debug (off by default)"
}

parse_commandline() {
  _positionals_count=0
  local _key
  while test $# -gt 0; do
    _key="$1"
    case "$_key" in
    -h | --help)
      print_help
      exit 0
      ;;
    -h*)
      print_help
      exit 0
      ;;
    --distance)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_distance="$2"
      shift
      ;;
    --distance=*)
      _arg_distance="${_key##--distance=}"
      ;;
    --levels)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_levels="$2"
      shift
      ;;
    --levels=*)
      _arg_levels="${_key##--levels=}"
      ;;
    --cycles)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_cycles="$2"
      shift
      ;;
    --cycles=*)
      _arg_cycles="${_key##--cycles=}"
      ;;
    --iters)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_iters="$2"
      shift
      ;;
    --iters=*)
      _arg_iters="${_key##--iters=}"
      ;;
    --lambda)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_lambda="$2"
      shift
      ;;
    --lambda=*)
      _arg_lambda="${_key##--lambda=}"
      ;;
    --fwhm)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_fwhm="$2"
      shift
      ;;
    --fwhm=*)
      _arg_fwhm="${_key##--fwhm=}"
      ;;
    --stop)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_stop="$2"
      shift
      ;;
    --stop=*)
      _arg_stop="${_key##--stop=}"
      ;;
    --isostep)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_isostep="$2"
      shift
      ;;
    --isostep=*)
      _arg_isostep="${_key##--isostep=}"
      ;;
    --no-big-misorientation | --big-misorientation)
      _arg_big_misorientation="on"
      test "${1:0:5}" = "--no-" && _arg_big_misorientation="off"
      ;;
    --model)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_model="$2"
      shift
      ;;
    --model=*)
      _arg_model="${_key##--model=}"
      ;;
    --model-mask)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_model_mask="$2"
      shift
      ;;
    --model-mask=*)
      _arg_model_mask="${_key##--model-mask=}"
      ;;
    -c | --no-clobber | --clobber)
      _arg_clobber="on"
      test "${1:0:5}" = "--no-" && _arg_clobber="off"
      ;;
    -c*)
      _arg_clobber="on"
      _next="${_key##-c}"
      if test -n "$_next" -a "$_next" != "$_key"; then
        { begins_with_short_option "$_next" && shift && set -- "-c" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
      fi
      ;;
    -v | --no-verbose | --verbose)
      _arg_verbose="on"
      test "${1:0:5}" = "--no-" && _arg_verbose="off"
      ;;
    -v*)
      _arg_verbose="on"
      _next="${_key##-v}"
      if test -n "$_next" -a "$_next" != "$_key"; then
        { begins_with_short_option "$_next" && shift && set -- "-v" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
      fi
      ;;
    -d | --no-debug | --debug)
      _arg_debug="on"
      test "${1:0:5}" = "--no-" && _arg_debug="off"
      ;;
    -d*)
      _arg_debug="on"
      _next="${_key##-d}"
      if test -n "$_next" -a "$_next" != "$_key"; then
        { begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
      fi
      ;;
    *)
      _last_positional="$1"
      _positionals+=("$_last_positional")
      _positionals_count=$((_positionals_count + 1))
      ;;
    esac
    shift
  done
}

handle_passed_args_count() {
  local _required_args_string="'input' and 'output'"
  test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
  test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}

assign_positional_args() {
  local _positional_name _shift_for=$1
  _positional_names="_arg_input _arg_output "

  shift "$_shift_for"
  for _positional_name in ${_positional_names}; do
    test $# -gt 0 || break
    eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
    shift
  done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

set -uo pipefail
set -eE -o functrace

# Add handler for failure to show where things went wrong
failure_handler() {
  local lineno=$2
  local fn=$3
  local exitstatus=$4
  local msg=$5
  local lineno_fns=${1% 0}
  if [[ "$lineno_fns" != "0" ]]; then
    lineno="${lineno} ${lineno_fns}"
  fi
  echo "${BASH_SOURCE[1]}:${fn}[${lineno}] Failed with status ${exitstatus}: $msg"
}
trap 'failure_handler "${BASH_LINENO[*]}" "$LINENO" "${FUNCNAME[*]:-script}" "$?" "$BASH_COMMAND"' ERR

tmpdir=$(mktemp -d)

# Setup exit trap for cleanup, don't do if debug
function finish() {
  if [[ ${_arg_debug} == "off" ]]; then
    rm -rf "${tmpdir}"
  else
    echo "Debug enabled, temporary files at ${tmpdir} have not been cleaned up"
  fi
}
trap finish EXIT

# Calculator used everywhere
function calc() { awk "BEGIN{ printf $* }"; }

function extension_strip() {
  sed -r 's/(.nii$|.nii.gz|.nrrd|.mnc|.mnc.gz)+$//'
}

lsq12_to_lsq6() {
  local input=$1
  local output=$2

  local tmpdir=$(mktemp -d)

  param2xfm $(xfm2param ${input} | grep -E 'scale|shear') ${tmpdir}/scaleshear.xfm
  xfminvert ${tmpdir}/scaleshear.xfm ${tmpdir}/unscaleshear.xfm
  xfmconcat ${input} ${tmpdir}/unscaleshear.xfm ${output}

  rm -rf ${tmpdir}
}

# Iterative multi-scale N3 implementation
hierarchical_N3() {
  local input=${1}
  local weight=${2}
  local fovmask=${3}
  local starting_distance=${4}
  local n3_levels=${5}
  local cycles=${6}
  local iters=${7}
  local output=${8}
  local field_output=${9}
  local tmpdir=$(mktemp -d)

  cp ${input} ${tmpdir}/input.mnc
  input=${tmpdir}/input.mnc

  minc_anlm --short --mt $(nproc) ${input} ${tmpdir}/denoised.mnc
  ResampleImage 3 ${tmpdir}/denoised.mnc ${tmpdir}/isoinput.mnc ${_arg_isostep}x${_arg_isostep}x${_arg_isostep} 0 1 3
  n3input=${tmpdir}/isoinput.mnc

  minccalc -clobber -unsigned -byte -expression 'A[0]>1?1:0' ${tmpdir}/isoinput.mnc ${tmpdir}/nonzero.mnc
  antsApplyTransforms -d 3 -i ${weight} -o ${tmpdir}/tmpweight.mnc -r ${n3input} -n GenericLabel
  ImageMath 3 ${tmpdir}/tmpweight.mnc m ${tmpdir}/tmpweight.mnc ${tmpdir}/nonzero.mnc

  distance=${starting_distance}

  j=0
  while ((j < n3_levels)); do
    i=0
    while ((i < cycles)); do
      nu_correct -normalize_field \
        -stop ${_arg_stop} -distance ${distance} -iterations ${iters} -fwhm ${_arg_fwhm} -shrink 1 -lambda ${_arg_lambda} \
        -mask ${tmpdir}/tmpweight.mnc ${n3input} ${tmpdir}/corrected_${distance}_${i}.mnc

      n3input=${tmpdir}/corrected_${distance}_${i}.mnc

      ((++i))
    done
    distance=$(calc "${distance} / 2")
    ((++j))
  done

  for file in ${tmpdir}/*imp; do
    echo evaluate_field -unsigned -double -clobber -like ${input} ${file} ${tmpdir}/$(basename ${file} .imp)_field.mnc
  done | parallel -j $(nproc)

  mincmath -clobber -unsigned -double -mult ${tmpdir}/*_field.mnc ${tmpdir}/field_combined.mnc

  correct_field ${tmpdir}/field_combined.mnc ${fovmask} ${tmpdir}/field_combined_correct.mnc

  minccalc -clobber -unsigned -int -expression "A[0]/A[1]" ${input} \
    ${tmpdir}/field_combined_correct.mnc ${output}

  cp -f ${tmpdir}/field_combined_correct.mnc ${field_output}
  rm -rf ${tmpdir}
}

MODEL=${_arg_model}
MODELMASK=${_arg_model_mask}

if [[ "$_arg_input" == *.nii || "$_arg_input" == *.nii.gz || "$_arg_input" == *.nrrd ]]; then
  ConvertImage 3 ${_arg_input} ${tmpdir}/input.nii.gz
  nii2mnc -quiet ${tmpdir}/input.nii.gz ${tmpdir}/input.mnc
  input=${tmpdir}/input.mnc
else
  input=${_arg_input}
fi

# Calulate a scaling factor for mm from isostep
dx=$(mincinfo -attvalue xspace:step ${input})
dy=$(mincinfo -attvalue yspace:step ${input})
dz=$(mincinfo -attvalue zspace:step ${input})
scale_factor=$(python -c "print(1.0 / ( ( abs(${dx}) + abs(${dy}) + abs(${dz}) ) / 3.0 ))")
min_stepsize=$(python -c "print(min(abs(${dx}),abs(${dy}),abs(${dz})))")

# Change the slicing direction to be the same as what ITK outputs by default
mincreshape -dimorder zspace,yspace,xspace +direction ${input} ${tmpdir}/reshape1.mnc
mincreshape -dimorder zspace,yspace,xspace +direction ${tmpdir}/reshape1.mnc ${tmpdir}/reshape2.mnc
rm -f ${tmpdir}/reshape1.mnc

# Store the direction cosine transform because we're going to zero out the file
dircos_to_xfm ${tmpdir}/reshape2.mnc ${tmpdir}/transform_to_input.xfm
# Square up direction cosines
minc_modify_header -dinsert xspace:direction_cosines=1,0,0 ${tmpdir}/reshape2.mnc
minc_modify_header -dinsert yspace:direction_cosines=0,1,0 ${tmpdir}/reshape2.mnc
minc_modify_header -dinsert zspace:direction_cosines=0,0,1 ${tmpdir}/reshape2.mnc

# Check if input image is zero-centered
if [[ $(calc "$(mincstats -quiet -floor 0 -percent ${tmpdir}/reshape2.mnc) < 50") == 1 ]]; then
  echo "Input file appears to be zero-centered, skipping clamping"
  mincnorm -out_ceil 65535 -out_floor 0 -short -cutoff 0.001 ${tmpdir}/reshape2.mnc ${tmpdir}/norm_input.mnc
else
  # Clamp above 0 and normalize using 0.1% histogram
  mincmath -unsigned -clamp -const2 0 1.79769e+308 ${tmpdir}/reshape2.mnc ${tmpdir}/clamp.mnc
  mincnorm -out_ceil 65535 -out_floor 0 -short -cutoff 0.001 ${tmpdir}/clamp.mnc ${tmpdir}/norm_input.mnc
fi

# Pad a little bit to avoid edge effects
volpad -distance $(calc "int(${scale_factor}*1.5)") ${tmpdir}/norm_input.mnc ${tmpdir}/norm_input_padded.mnc

input=${tmpdir}/norm_input_padded.mnc
minc_anlm --short --mt $(nproc) ${input} ${tmpdir}/norm_input_padded_denoise.mnc
input_denoise=${tmpdir}/norm_input_padded_denoise.mnc

################################################################################

# Construct a foreground mask using Otsu thresholding
minccalc -unsigned -byte -expression 'A[0]>0?1:0' ${input_denoise} ${tmpdir}/nonzero.mnc
ThresholdImage 3 ${input_denoise} ${tmpdir}/fgmask.mnc Otsu 4 ${tmpdir}/nonzero.mnc
ThresholdImage 3 ${tmpdir}/fgmask.mnc ${tmpdir}/fgmask.mnc 1.5 Inf 1 0
ImageMath 3 ${tmpdir}/fgmask.mnc GetLargestComponent ${tmpdir}/fgmask.mnc

# cp ${tmpdir}/fgmask.mnc $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_initial_mask.mnc

# Precorrect Round 1
hierarchical_N3 ${input} ${tmpdir}/fgmask.mnc ${tmpdir}/fgmask.mnc 40 2 ${_arg_cycles} ${_arg_iters} ${tmpdir}/precorrect1.mnc ${tmpdir}/precorrect1_field.mnc

################################################################################

minc_anlm --short --mt $(nproc) ${tmpdir}/precorrect1.mnc ${tmpdir}/precorrect1_denoise.mnc

# Reconstruct a foreground mask using Otsu thresholding
minccalc -clobber -unsigned -byte -expression 'A[0]>0?1:0' ${input_denoise} ${tmpdir}/nonzero.mnc
ThresholdImage 3 ${tmpdir}/precorrect1_denoise.mnc ${tmpdir}/fgmask.mnc Otsu 4 ${tmpdir}/nonzero.mnc
ThresholdImage 3 ${tmpdir}/fgmask.mnc ${tmpdir}/fgmask.mnc 1.5 Inf 1 0
ImageMath 3 ${tmpdir}/fgmask.mnc GetLargestComponent ${tmpdir}/fgmask.mnc
iMath 3 ${tmpdir}/fgmask.mnc MD ${tmpdir}/fgmask.mnc $(calc "int(${scale_factor}*0.2)") 1 ball 1
ImageMath 3 ${tmpdir}/fgmask.mnc FillHoles ${tmpdir}/fgmask.mnc 2
ThresholdImage 3 ${tmpdir}/precorrect1_denoise.mnc ${tmpdir}/fgweight.mnc Otsu 4 ${tmpdir}/fgmask.mnc
ThresholdImage 3 ${tmpdir}/fgweight.mnc ${tmpdir}/fgweight.mnc 1.5 Inf 1 0

ResampleImage 3 ${MODEL} ${tmpdir}/model_downsample.mnc 0.1x0.1x0.1 0
antsApplyTransforms -d 3 -i ${MODELMASK} -r ${tmpdir}/model_downsample.mnc \
  -n GenericLabel -o ${tmpdir}/model_mask.mnc

if [[ ${_arg_big_misorientation} == "on" ]]; then
  # Really rough registration
  SmoothImage 3 ${tmpdir}/precorrect1_denoise.mnc 0.3 ${tmpdir}/antsAI_subject.mnc 1
  SmoothImage 3 ${MODEL} 0.3 ${tmpdir}/antsAI_template.mnc 1

  ResampleImageBySpacing 3 ${tmpdir}/antsAI_subject.mnc ${tmpdir}/antsAI_subject.mnc 0.4 0.4 0.4 0
  ResampleImageBySpacing 3 ${tmpdir}/antsAI_template.mnc ${tmpdir}/antsAI_template.mnc 0.4 0.4 0.4 0

  mincmath -clobber -quiet -clamp -unsigned -short -const2 0 Inf ${tmpdir}/antsAI_subject.mnc ${tmpdir}/clamp.mnc
  mv ${tmpdir}/clamp.mnc ${tmpdir}/antsAI_subject.mnc

  mincmath -clobber -quiet -clamp -unsigned -short -const2 0 Inf ${tmpdir}/antsAI_template.mnc ${tmpdir}/clamp.mnc
  mv ${tmpdir}/clamp.mnc ${tmpdir}/antsAI_template.mnc

  antsAI -d 3 -v 1 \
    -m Mattes[ ${tmpdir}/antsAI_template.mnc,${tmpdir}/antsAI_subject.mnc,32,Random,0.5,1 ] \
    -t AlignCentersOfMass \
    -t Similarity[ 0.1 ] \
    -s [ 45,1 ] \
    -g [ 10,0x0x0 ] \
    -p 1 \
    -c 50 \
    -o ${tmpdir}/antsAI.mat


  # Register to model to use its foreground mask and FOV
  antsRegistration_affine_SyN.sh --skip-nonlinear \
    --initial-transform ${tmpdir}/antsAI.mat \
    --linear-type lsq9 \
    --fixed-mask ${tmpdir}/model_mask.mnc \
    ${tmpdir}/precorrect1_denoise.mnc \
    ${tmpdir}/model_downsample.mnc \
    ${tmpdir}/to_model_
else
  antsRegistration_affine_SyN.sh --skip-nonlinear \
    --linear-type lsq9 \
    --fixed-mask ${tmpdir}/model_mask.mnc \
    ${tmpdir}/precorrect1_denoise.mnc \
    ${tmpdir}/model_downsample.mnc \
    ${tmpdir}/to_model_
fi

mincreshape $(mincbbox -mincreshape ${MODEL}) ${MODEL} ${tmpdir}/model_fov.mnc
minccalc -unsigned -byte -expression '1' ${tmpdir}/model_fov.mnc ${tmpdir}/model_fovmask.mnc

# Pad a bunch so we can do an extraction
volpad -distance $(calc "int(${scale_factor}*5)") ${input} ${tmpdir}/padded_input.mnc
antsApplyTransforms -d 3 --verbose -n GenericLabel \
  -i ${tmpdir}/model_fovmask.mnc \
  -t [ ${tmpdir}/to_model_0_GenericAffine.xfm,1 ] \
  -o ${tmpdir}/subject_fovmask.mnc \
  -r ${tmpdir}/padded_input.mnc

antsApplyTransforms -d 3 -n GenericLabel \
  -r ${tmpdir}/padded_input.mnc \
  -i ${tmpdir}/fgmask.mnc \
  -o ${tmpdir}/fgmask.mnc

ImageMath 3 ${tmpdir}/padded_input_extracted.mnc m ${tmpdir}/padded_input.mnc ${tmpdir}/subject_fovmask.mnc

# Extract using the FOV
ExtractRegionFromImageByMask 3 ${tmpdir}/padded_input_extracted.mnc \
  ${tmpdir}/norm_input_extracted_repad.mnc ${tmpdir}/subject_fovmask.mnc 1 0

antsApplyTransforms -d 3 -n GenericLabel \
  -i ${tmpdir}/fgweight.mnc \
  -r ${tmpdir}/norm_input_extracted_repad.mnc \
  -o ${tmpdir}/fgweight.mnc

# Start again using the corrected FOV input
input=${tmpdir}/norm_input_extracted_repad.mnc

# Precorrect Round 2
hierarchical_N3 ${input} ${tmpdir}/fgweight.mnc ${tmpdir}/fgweight.mnc 40 2 ${_arg_cycles} ${_arg_iters} \
  ${tmpdir}/precorrect2.mnc ${tmpdir}/precorrect2_field.mnc

################################################################################

minc_anlm --short --mt $(nproc) ${tmpdir}/precorrect2.mnc ${tmpdir}/precorrect2_denoise.mnc

antsRegistration_affine_SyN.sh --clobber --skip-nonlinear \
  --initial-transform ${tmpdir}/to_model_0_GenericAffine.xfm \
  --close \
  --fixed-mask ${tmpdir}/model_mask.mnc \
  ${tmpdir}/precorrect2_denoise.mnc \
  ${tmpdir}/model_downsample.mnc \
  ${tmpdir}/to_model_2_

antsRegistration_affine_SyN.sh --skip-linear --clobber \
  --syn-metric CC[2] \
  --syn-control 0.2,3,0 \
  --initial-transform ${tmpdir}/to_model_2_0_GenericAffine.xfm \
  --fixed-mask ${tmpdir}/model_mask.mnc \
  ${tmpdir}/precorrect2_denoise.mnc \
  ${tmpdir}/model_downsample.mnc \
  ${tmpdir}/to_model_2_

antsApplyTransforms -d 3 \
  -n GenericLabel \
  -i ${MODELMASK} \
  -r ${tmpdir}/precorrect2_denoise.mnc \
  -t [ ${tmpdir}/to_model_2_0_GenericAffine.xfm,1 ] \
  -t ${tmpdir}/to_model_2_1_inverse_NL.xfm \
  -o ${tmpdir}/subject_mask.mnc

ThresholdImage 3 ${tmpdir}/precorrect2_denoise.mnc ${tmpdir}/final_weight.mnc Otsu 4 ${tmpdir}/subject_mask.mnc
ThresholdImage 3 ${tmpdir}/final_weight.mnc ${tmpdir}/final_weight.mnc 1.5 Inf 1 0

hierarchical_N3 ${tmpdir}/precorrect2.mnc ${tmpdir}/final_weight.mnc ${tmpdir}/fgmask.mnc \
  ${_arg_distance} ${_arg_levels} ${_arg_cycles} ${_arg_iters} \
  ${tmpdir}/corrected.mnc ${tmpdir}/correct_field.mnc

################################################################################

# Correct the original input brain to have mean 32767
origmean=$(mincstats -mean -quiet -mask ${tmpdir}/subject_mask.mnc -mask_binvalue 1 ${input})
minccalc -clobber -unsigned -int -expression "clamp(((A[0]/${origmean})/(A[1]*A[2]))*32767,0,65535)" \
  ${input} ${tmpdir}/precorrect2_field.mnc ${tmpdir}/correct_field.mnc ${tmpdir}/corrected.mnc

minc_anlm --short --mt $(nproc) ${tmpdir}/corrected.mnc ${tmpdir}/corrected_denoise.mnc
mincmath -clamp -const2 0 Inf ${tmpdir}/corrected_denoise.mnc ${tmpdir}/corrected_denoise_clamp.mnc
mv -f ${tmpdir}/corrected_denoise_clamp.mnc ${tmpdir}/corrected_denoise.mnc

antsApplyTransforms -d 3 -n GenericLabel \
  -i ${tmpdir}/subject_mask.mnc \
  -r ${tmpdir}/corrected_denoise.mnc \
  -o ${tmpdir}/subject_mask_resample.mnc

lsq12_to_lsq6 ${tmpdir}/to_model_2_0_GenericAffine.xfm ${tmpdir}/lsq6.xfm

mincresample -clobber -keep -unsigned -short -tfm_input_sampling -transform ${tmpdir}/transform_to_input.xfm ${tmpdir}/corrected_denoise.mnc \
  ${tmpdir}/output.mnc

mincresample -clobber -keep -near -labels -unsigned -byte -tfm_input_sampling -transform ${tmpdir}/transform_to_input.xfm ${tmpdir}/subject_mask_resample.mnc \
  ${tmpdir}/output_mask.mnc

mincresample -clobber -keep -unsigned -short -invert_transform -tfm_input_sampling -transform ${tmpdir}/lsq6.xfm ${tmpdir}/corrected_denoise.mnc \
  ${tmpdir}/output_lsq6.mnc

mincresample -clobber -keep -near -labels -unsigned -byte -invert_transform -tfm_input_sampling -transform ${tmpdir}/lsq6.xfm ${tmpdir}/subject_mask_resample.mnc \
  ${tmpdir}/output_lsq6_mask.mnc

if [[ "$_arg_output" == *.nii ]]; then
  mnc2nii ${tmpdir}/output.mnc ${_arg_output}
  mnc2nii ${tmpdir}/output_mask.mnc $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_mask.nii
  mnc2nii ${tmpdir}/output_lsq6.mnc $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_lsq6.nii
  mnc2nii ${tmpdir}/output_lsq6_mask.mnc $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_lsq6_mask.nii
elif [[ "$_arg_output" == *.nii.gz ]]; then
  mnc2nii ${tmpdir}/output.mnc ${tmpdir}/output.nii
  mnc2nii ${tmpdir}/output_mask.mnc ${tmpdir}/output_mask.nii
  mnc2nii ${tmpdir}/output_lsq6.mnc ${tmpdir}/output_lsq6.nii
  mnc2nii ${tmpdir}/output_lsq6_mask.mnc ${tmpdir}/output_lsq6_mask.nii
  gzip ${tmpdir}/output*nii
  cp -f ${tmpdir}/output.nii.gz ${_arg_output}
  cp -f ${tmpdir}/output_mask.nii.gz $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_mask.nii.gz
  cp -f ${tmpdir}/output_lsq6.nii.gz $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_lsq6.nii.gz
  cp -f ${tmpdir}/output_lsq6_mask.nii.gz $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_lsq6_mask.nii.gz
elif [[ "$_arg_output" == *.mnc ]]; then
  cp -f ${tmpdir}/output.mnc ${_arg_output}
  cp -f ${tmpdir}/output_mask.mnc $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_mask.mnc
  cp -f ${tmpdir}/output_lsq6.mnc $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_lsq6.mnc
  cp -f ${tmpdir}/output_lsq6_mask.mnc $(dirname ${_arg_output})/$(basename ${_arg_output} | extension_strip)_lsq6_mask.mnc
fi

# ] <-- needed because of Argbash
